export const PRESETS = [
  {
    id: "dreamy-pad",
    name: "Dreamy Pad",
    seed: 48291,
    bpm: 92,
    mode: "pad",
    sound: "pad",
    chords: ["Am9", "Fmaj7", "Cadd9", "Gsus4"],
    core: {
      ghostAmount: 48,
      drift: 35,
      harmonyLock: 68,
      colorMode: "dreamy",
      stayMusical: true,
      ghostEnabled: true,
      voicingStyle: "open",
      voicingVariation: 35,
      voicingContinuity: 65,
      arpDirection: "up",
      arpFeel: "even",
      arpDensity: 50,
      arpContinuity: 60,
    },
    soundControls: {
      waveform: "triangle",
      cutoff: 1800,
      attack: 0.28,
      release: 0.7,
      space: 18,
    },
  },
  {
    id: "warm-bed",
    name: "Warm Bed",
    seed: 19377,
    bpm: 78,
    mode: "pad",
    sound: "pad",
    chords: ["Cmaj7", "Am9", "Fmaj7", "Gsus4"],
    core: {
      ghostAmount: 30,
      drift: 18,
      harmonyLock: 82,
      colorMode: "warm",
      stayMusical: true,
      ghostEnabled: true,
      voicingStyle: "smooth",
      voicingVariation: 18,
      voicingContinuity: 88,
      arpDirection: "up",
      arpFeel: "even",
      arpDensity: 35,
      arpContinuity: 82,
    },
    soundControls: {
      waveform: "sine",
      cutoff: 1400,
      attack: 0.45,
      release: 1.2,
      space: 12,
    },
  },
  {
    id: "dark-drift",
    name: "Dark Drift",
    seed: 70842,
    bpm: 86,
    mode: "evolve",
    sound: "pad",
    chords: ["Dm9", "Bbmaj7", "Gm9", "Asus4"],
    core: {
      ghostAmount: 64,
      drift: 78,
      harmonyLock: 52,
      colorMode: "dark",
      stayMusical: true,
      ghostEnabled: true,
      voicingStyle: "spread",
      voicingVariation: 42,
      voicingContinuity: 55,
      arpDirection: "insideout",
      arpFeel: "flowing",
      arpDensity: 56,
      arpContinuity: 50,
    },
    soundControls: {
      waveform: "triangle",
      cutoff: 1050,
      attack: 0.38,
      release: 1.45,
      space: 22,
    },
  },
  {
    id: "broken-arp",
    name: "Broken Arp",
    seed: 61007,
    bpm: 118,
    mode: "arp",
    sound: "pluck",
    chords: ["Em9", "Gmaj7", "Dadd9", "A7"],
    core: {
      ghostAmount: 42,
      drift: 22,
      harmonyLock: 62,
      colorMode: "dreamy",
      stayMusical: true,
      ghostEnabled: true,
      voicingStyle: "open",
      voicingVariation: 52,
      voicingContinuity: 48,
      arpDirection: "bounce",
      arpFeel: "broken",
      arpDensity: 78,
      arpContinuity: 38,
    },
    soundControls: {
      waveform: "square",
      cutoff: 3200,
      attack: 0.03,
      release: 0.22,
      space: 8,
    },
  },
  {
    id: "ambient-pad",
    name: "Ambient Pad",
    seed: 33814,
    bpm: 76,
    mode: "pad",
    sound: "pad",
    chords: ["Amaj7", "F#m9", "Dmaj9", "Bm7"],
    core: {
      generatorMode: "infinite",
      harmonicMotion: 5,
      ghostAmount: 52,
      drift: 42,
      harmonyLock: 74,
      colorMode: "dreamy",
      stayMusical: true,
      ghostEnabled: true,
      voicingStyle: "open",
      voicingVariation: 22,
      voicingContinuity: 78,
      arpDirection: "up",
      arpFeel: "even",
      arpDensity: 40,
      arpContinuity: 72,
      memoryStrength: 65,
    },
    soundControls: {
      waveform: "triangle",
      cutoff: 1600,
      attack: 0.18,
      release: 0.95,
      space: 24,
      reverbMix: 42,
      delayMix: 5,
    },
  },
  {
    id: "soft-arp",
    name: "Soft Arp",
    seed: 55290,
    bpm: 100,
    mode: "arp",
    sound: "pluck",
    chords: ["Em9", "Cmaj7", "G6", "Dsus4"],
    core: {
      generatorMode: "infinite",
      harmonicMotion: 55,
      ghostAmount: 38,
      drift: 28,
      harmonyLock: 60,
      colorMode: "warm",
      stayMusical: true,
      ghostEnabled: true,
      voicingStyle: "open",
      voicingVariation: 44,
      voicingContinuity: 52,
      arpDirection: "up",
      arpFeel: "flowing",
      arpDensity: 72,
      arpContinuity: 55,
      memoryStrength: 45,
    },
    soundControls: {
      waveform: "sawtooth",
      cutoff: 2400,
      attack: 0.02,
      release: 0.28,
      space: 14,
      reverbMix: 18,
      delayMix: 28,
    },
  },
  {
    id: "evolve-lead",
    name: "Evolve Lead",
    seed: 77621,
    bpm: 88,
    mode: "evolve",
    sound: "pad",
    chords: ["Dm9", "Bbmaj7", "Gm9", "Cm7"],
    core: {
      generatorMode: "infinite",
      harmonicMotion: 30,
      ghostAmount: 58,
      drift: 52,
      harmonyLock: 56,
      colorMode: "dark",
      stayMusical: true,
      ghostEnabled: true,
      voicingStyle: "spread",
      voicingVariation: 36,
      voicingContinuity: 60,
      arpDirection: "up",
      arpFeel: "flowing",
      arpDensity: 55,
      arpContinuity: 58,
      memoryStrength: 38,
    },
    soundControls: {
      waveform: "sawtooth",
      cutoff: 2200,
      attack: 0.06,
      release: 0.55,
      space: 20,
      reverbMix: 28,
      delayMix: 12,
    },
  },
];

export function findPreset(id) {
  return PRESETS.find((preset) => preset.id === id) || PRESETS[0];
}

