export const PRESETS = [
  {
    id: "dreamy-pad",
    name: "Dreamy Pad",
    seed: 48291,
    bpm: 92,
    mode: "pad",
    sound: "pad",
    chords: ["Am9", "Fmaj7", "Cadd9", "Gsus4"],
    core: {
      ghostAmount: 48,
      drift: 35,
      harmonyLock: 68,
      colorMode: "dreamy",
      stayMusical: true,
      ghostEnabled: true,
      voicingStyle: "open",
      voicingVariation: 35,
      voicingContinuity: 65,
      arpDirection: "up",
      arpFeel: "even",
      arpDensity: 50,
      arpContinuity: 60,
    },
    soundControls: {
      waveform: "triangle",
      cutoff: 1800,
      attack: 0.28,
      release: 0.7,
      space: 22,
      reverbMix: 34,
      delayMix: 8,
    },
  },
  {
    id: "warm-bed",
    name: "Warm Bed",
    seed: 19377,
    bpm: 78,
    mode: "pad",
    sound: "pad",
    chords: ["Cmaj7", "Am9", "Fmaj7", "Gsus4"],
    core: {
      ghostAmount: 28,
      drift: 16,
      harmonyLock: 84,
      colorMode: "warm",
      stayMusical: true,
      ghostEnabled: true,
      voicingStyle: "smooth",
      voicingVariation: 20,
      voicingContinuity: 88,
      arpDirection: "up",
      arpFeel: "even",
      arpDensity: 34,
      arpContinuity: 84,
    },
    soundControls: {
      waveform: "sine",
      cutoff: 1450,
      attack: 0.42,
      release: 1.25,
      space: 18,
      reverbMix: 38,
      delayMix: 4,
    },
  },
  {
    id: "nocturne-current",
    name: "Nocturne Current",
    seed: 70842,
    bpm: 84,
    mode: "pad",
    sound: "pad",
    chords: ["Dm9", "Bbmaj7", "Gm9", "Asus4"],
    core: {
      generatorMode: "infinite",
      harmonicMotion: 18,
      ghostAmount: 62,
      drift: 60,
      harmonyLock: 58,
      colorMode: "dark",
      stayMusical: true,
      ghostEnabled: true,
      voicingStyle: "spread",
      voicingVariation: 58,
      voicingContinuity: 72,
      arpDirection: "insideout",
      arpFeel: "flowing",
      arpDensity: 42,
      arpContinuity: 56,
      globalRoot: "2",
      scaleName: "minor",
      scaleInfluence: 46,
      memoryStrength: 56,
    },
    soundControls: {
      waveform: "triangle",
      cutoff: 1120,
      attack: 0.36,
      release: 1.5,
      space: 28,
      reverbMix: 46,
      delayMix: 12,
    },
  },
  {
    id: "broken-arp",
    name: "Broken Arp",
    seed: 61007,
    bpm: 116,
    mode: "arp",
    sound: "pluck",
    chords: ["Em9", "Gmaj7", "Dadd9", "A7"],
    core: {
      generatorMode: "infinite",
      harmonicMotion: 62,
      ghostAmount: 40,
      drift: 24,
      harmonyLock: 60,
      colorMode: "dreamy",
      stayMusical: true,
      ghostEnabled: true,
      voicingStyle: "open",
      voicingVariation: 60,
      voicingContinuity: 42,
      arpDirection: "bounce",
      arpFeel: "broken",
      arpDensity: 80,
      arpContinuity: 40,
      memoryStrength: 34,
      globalRoot: "4",
      scaleName: "minor",
      scaleInfluence: 32,
    },
    soundControls: {
      waveform: "square",
      cutoff: 3200,
      attack: 0.03,
      release: 0.24,
      space: 12,
      reverbMix: 30,
      delayMix: 24,
    },
  },
  {
    id: "local-weave",
    name: "Local Weave",
    seed: 33814,
    bpm: 76,
    mode: "pad",
    sound: "pad",
    chords: ["Amaj7", "F#m9", "Dmaj9", "Bm7"],
    core: {
      generatorMode: "infinite",
      harmonicMotion: 12,
      ghostAmount: 50,
      drift: 40,
      harmonyLock: 74,
      colorMode: "dreamy",
      stayMusical: true,
      ghostEnabled: true,
      voicingStyle: "open",
      voicingVariation: 24,
      voicingContinuity: 84,
      localScaleType: "major",
      localTargetDegree: 5,
      localDegreeFalloff: 1,
      arpDirection: "up",
      arpFeel: "even",
      arpDensity: 36,
      arpContinuity: 74,
      globalRoot: "9",
      scaleName: "major",
      scaleInfluence: 54,
      memoryStrength: 60,
    },
    soundControls: {
      waveform: "triangle",
      cutoff: 1600,
      attack: 0.18,
      release: 1.05,
      space: 26,
      reverbMix: 44,
      delayMix: 6,
    },
  },
  {
    id: "open-canopy",
    name: "Open Canopy",
    seed: 55290,
    bpm: 96,
    mode: "pad",
    sound: "pad",
    chords: ["Em9", "Cmaj7", "G6", "Dsus4"],
    core: {
      generatorMode: "infinite",
      harmonicMotion: 18,
      ghostAmount: 44,
      drift: 32,
      harmonyLock: 62,
      colorMode: "warm",
      stayMusical: true,
      ghostEnabled: true,
      voicingStyle: "open",
      voicingVariation: 72,
      voicingContinuity: 74,
      localScaleType: "major",
      localTargetDegree: 3,
      localDegreeFalloff: 1,
      arpDirection: "up",
      arpFeel: "flowing",
      arpDensity: 44,
      arpContinuity: 60,
      globalRoot: "4",
      scaleName: "minor",
      scaleInfluence: 36,
      memoryStrength: 42,
      registerCenter: 62,
    },
    soundControls: {
      waveform: "triangle",
      cutoff: 1950,
      attack: 0.14,
      release: 0.92,
      space: 24,
      reverbMix: 40,
      delayMix: 10,
    },
  },
  {
    id: "tight-orbit",
    name: "Tight Orbit",
    seed: 77621,
    bpm: 90,
    mode: "pad",
    sound: "pad",
    chords: ["Dm9", "Bbmaj7", "Gm9", "Cm7"],
    core: {
      generatorMode: "infinite",
      harmonicMotion: 82,
      ghostAmount: 46,
      drift: 30,
      harmonyLock: 70,
      colorMode: "dark",
      stayMusical: true,
      ghostEnabled: true,
      voicingStyle: "smooth",
      voicingVariation: 18,
      voicingContinuity: 90,
      arpDirection: "up",
      arpFeel: "even",
      arpDensity: 36,
      arpContinuity: 72,
      globalRoot: "2",
      scaleName: "minor",
      scaleInfluence: 48,
      memoryStrength: 46,
    },
    soundControls: {
      waveform: "sawtooth",
      cutoff: 1700,
      attack: 0.08,
      release: 0.68,
      space: 18,
      reverbMix: 36,
      delayMix: 8,
    },
  },
  {
    id: "wide-orbit",
    name: "Wide Orbit",
    seed: 88413,
    bpm: 102,
    mode: "pad",
    sound: "pad",
    chords: ["Bm11", "Gmaj7", "Dadd9", "A6"],
    core: {
      generatorMode: "infinite",
      harmonicMotion: 78,
      ghostAmount: 52,
      drift: 34,
      harmonyLock: 54,
      colorMode: "dreamy",
      stayMusical: true,
      ghostEnabled: true,
      voicingStyle: "spread",
      voicingVariation: 78,
      voicingContinuity: 82,
      arpDirection: "up",
      arpFeel: "flowing",
      arpDensity: 46,
      arpContinuity: 64,
      globalRoot: "11",
      scaleName: "minor",
      scaleInfluence: 40,
      memoryStrength: 38,
      registerCenter: 61,
    },
    soundControls: {
      waveform: "triangle",
      cutoff: 2100,
      attack: 0.12,
      release: 0.88,
      space: 24,
      reverbMix: 42,
      delayMix: 14,
    },
  },
];

export function findPreset(id) {
  return PRESETS.find((preset) => preset.id === id) || PRESETS[0];
}
